image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
- name: Drupal Website
  port: 8888
  onOpen: open-browser
- port: 3306
  onOpen: ignore
- name: Mailhog
  port: 8025
  onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals.
# See https://www.gitpod.io/docs/config-start-tasks/
tasks:
- before: ln -sf ~/bin/adminer.php web/adminer.php
  command: sleep 45 && source ~/.bashrc && ((mysql -e "CREATE USER 'db'@'localhost' IDENTIFIED by 'db';" && mysql -e "GRANT ALL PRIVILEGES ON *.* to 'db'@'localhost';" && mysql -e "CREATE DATABASE db;" && mysql -e "FLUSH PRIVILEGES;") && drush sqlc < ./umami_db.sql); drush cr && drush user:pass admin pass && drush cim -y ; drush rs 0.0.0.0:8888
  name: Server
- command: source ~/.bashrc && (docker run --restart always -d --name=mailhog -p 1025:1025 -p 8025:8025 mailhog/mailhog)
  name: "Install mailhog"
- command: echo "Welcome, please allow Server terminal to finish drupal install. It takes a while!" && gp ports await 8888 && drush uli --uri=$(gp url 8888)
  name: "Drush & Bash"

vscode:
  extensions:
    # PHP extensions.
    - xdebug.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - andrewdavidblum.drupal-smart-snippets
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2
