maillog.settings:
  type: config_object
  mapping:
    send:
      type: boolean
      label: Send emails
    nosend_notify:
      type: boolean
      label: Notify visitor that emails are not being sent
    log:
      type: boolean
      label: Log emails
    log_notify:
      type: boolean
      label: Notify visitor that emails are being logged
    verbose:
      type: boolean
      label: Display mails
    body_trimmed:
      type: boolean
      label: 'Body trimmed'
    base64_remove:
      type: boolean
      label: 'Remove base64 from body'
    cron_enabled:
      type: boolean
      label: 'Enable the cron'
    keep_limit_type:
      type: string
      label: 'Keep backup type'
    time_to_keep:
      type: integer
      label: 'The time to keep the backups in days'
    number_to_keep:
      type: integer
      label: 'Number of backups to keep'
